import type { ResearchFilters } from "@/types/research";

export const MAX_RESEARCH_REQUEST_LENGTH = 4_000;

export const INITIAL_FILTERS: ResearchFilters = {
  query: "",
  fromYear: "",
  toYear: "",
  workType: "all",
  openAccess: "all",
  language: "all",
  author: "",
  institution: "",
  source: "",
  sort: "relevance",
};

export const RESEARCH_TOPIC_POOL = [
  "Urban green spaces and mental health",
  "Sleep and memory consolidation",
  "Sustainable battery materials",
  "Climate change and food security",
  "Artificial intelligence in medical diagnosis",
  "Microplastics in marine ecosystems",
  "Remote work and employee wellbeing",
  "Renewable energy storage",
  "Antibiotic resistance",
  "Social media and adolescent wellbeing",
  "Biodiversity loss and ecosystem resilience",
  "Personalized cancer treatment",
  "Quantum computing applications",
  "Early childhood language development",
  "Air pollution and public health",
  "Circular economy business models",
  "Neuroplasticity after stroke",
  "Digital twins in urban planning",
  "Misinformation and public trust",
  "Precision agriculture",
  "Gene editing ethics",
  "Ocean acidification",
  "Autonomous vehicles and road safety",
  "Exercise and cognitive aging",
  "Carbon capture technologies",
  "Housing affordability and inequality",
  "Human-robot collaboration",
  "Gut microbiome and mental health",
  "Green hydrogen production",
  "Inclusive education practices",
  "Wildfire prediction and management",
  "Blockchain in supply chains",
  "Maternal health disparities",
  "Nature-based climate solutions",
  "Cybersecurity behavior",
  "Music and emotion regulation",
  "Water scarcity adaptation",
  "Telemedicine outcomes",
  "Sustainable architecture",
  "Migration and labor markets",
  "Machine learning interpretability",
  "Coral reef restoration",
  "Loneliness and physical health",
  "Smart grid resilience",
  "Educational technology effectiveness",
  "Parkinson’s disease biomarkers",
  "Urban heat island mitigation",
  "Algorithmic bias",
  "Regenerative agriculture",
  "Virtual reality in rehabilitation",
  "Democratic participation and polarization",
  "Solar cell efficiency",
  "Childhood trauma and adult health",
  "Flood risk management",
  "Language models in education",
  "Rare disease diagnosis",
  "Sustainable aviation fuels",
  "Workplace diversity and innovation",
  "Brain-computer interfaces",
  "Deforestation monitoring",
  "Nutrition and healthy aging",
  "Privacy-preserving machine learning",
  "Urban mobility and accessibility",
  "Vaccine hesitancy",
  "Biodegradable polymers",
  "Cultural heritage preservation",
  "Robotics in elderly care",
  "Drought-resistant crops",
  "Economic effects of automation",
  "Wearable health monitoring",
  "Mental health interventions for students",
  "Geothermal energy systems",
  "Open science and reproducibility",
  "Forest carbon sequestration",
  "Assistive technologies",
  "Political communication online",
  "Food waste reduction",
  "Epigenetics and environmental exposure",
  "Satellite imagery for disaster response",
  "Sustainable tourism",
  "Chronic pain management",
  "Internet access and social inequality",
  "Hydrogen fuel cells",
  "Pollinator decline",
  "Digital literacy",
  "Alzheimer’s disease prevention",
  "Coastal erosion adaptation",
  "Natural language processing in healthcare",
  "Public transportation equity",
  "Alternative proteins",
  "Emotional regulation in childhood",
  "Wastewater treatment innovation",
  "Citizen science",
  "Extreme weather attribution",
  "Financial inclusion technologies",
  "Indoor air quality",
  "Species reintroduction",
  "Creativity and artificial intelligence",
  "Community resilience after disasters",
  "Sustainable fashion",
];

export function sampleResearchTopics(count = 6): string[] {
  const topics = [...RESEARCH_TOPIC_POOL];
  for (let index = topics.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [topics[index], topics[swapIndex]] = [topics[swapIndex], topics[index]];
  }
  return topics.slice(0, count);
}
